const GET_CURRENT_COMIC = "GET_CURRENT_COMIC"
const TOGGLE_LIKE = "TOGGLE_LIKE"
const INCREASE_LIKE = "INCREASE_LIKE"
const DECREASE_LIKE = "DECREASE_LIKE"
const ADD_COMMENT = "ADD_COMMENT"

export { GET_CURRENT_COMIC, TOGGLE_LIKE, INCREASE_LIKE, DECREASE_LIKE, ADD_COMMENT }